[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme = 'light'
  "ã“ã“ã‹ã‚‰ã‚³ãƒ”ãƒš
  " â—‹ã‚„â–¡ã®æ–‡å­—ãŒå´©ã‚Œã‚‹å•é¡Œã‚’å›é¿
  set ambiwidth=double
  " Powerlineç³»ãƒ•ã‚©ãƒ³ãƒˆã‚’åˆ©ç”¨ã™ã‚‹
  set laststatus=2
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#whitespace#mixed_indent_algo = 1
  let g:airline_theme = 'papercolor'
  if !exists('g:airline_symbols')
    let g:airline_symbols = {}
  endif
  " unicode symbols
  let g:airline_left_sep = 'Â»'
  let g:airline_left_sep = 'â–¶'
  let g:airline_right_sep = 'Â«'
  let g:airline_right_sep = 'â—€'
  "let g:airline_symbols.crypt = 'ğŸ”’'
  "let g:airline_symbols.linenr = 'âŠ'
  "let g:airline_symbols.linenr = 'â¤'
  "let g:airline_symbols.linenr = 'Â¶'
  "let g:airline_symbols.maxlinenr = 'â˜°'
  "let g:airline_symbols.maxlinenr = ''
  "let g:airline_symbols.branch = 'â‡'
  "let g:airline_symbols.paste = 'Ï'
  "let g:airline_symbols.paste = 'Ã'
  "let g:airline_symbols.paste = 'âˆ¥'
  "let g:airline_symbols.spell = 'ê¨'
  "let g:airline_symbols.notexists = 'âˆ„'
  "let g:airline_symbols.whitespace = 'Î'
  " powerline symbols
  "let g:airline_left_sep = 'î‚°'
  "let g:airline_left_alt_sep = 'î‚±'
  "let g:airline_right_sep = 'î‚²'
  "let g:airline_right_alt_sep = 'î‚³'
  "let g:airline_symbols.branch = 'î‚ '
  "let g:airline_symbols.readonly = 'î‚¢'
  let g:airline_symbols.linenr = 'î‚¡'
  " old vim-powerline symbols
  let g:airline_left_sep = 'â®€'
  let g:airline_left_alt_sep = 'â®'
  let g:airline_right_sep = 'â®‚'
  let g:airline_right_alt_sep = 'â®ƒ'
  " let g:airline_symbols.branch = 'â­ '
  " let g:airline_symbols.readonly = 'â­¤'
  " let g:airline_symbols.linenr = 'â­¡'
  "ã‚³ãƒ”ãƒšã“ã“ã¾ã§
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'MetalPhaeton/easybracket-vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

#[[plugins]]
#repo = 'nathanaelkane/vim-indent-guides'
#hook_add = 'let g:indent_guides_enable_on_vim_startup = 1'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tomasr/molokai'
